### ISSUE TITLE
Work on node_tools.cc

### ISSUE THREAD

**Issue by Shibbywan** [reboss/RapidOnsetAdHocNetwork#14]
- [x] Function to get and set the node IDs
- [x] Function to detect connection loss
         <ul><li>send the info to the sink</li></ul>
- [ ] Function to setup (look at packet, set appropriate parameters)

**Comment by ElliottSobek** [comment]
NOTES: Functions to get and set node Id's do reside in different files. The current function to get node id's does not return anything, misleading intent. The current function to set node id's increments all three (3) node id's at once.

**Comment by ChrisDubeau** [comment]
Notes: get id functions all in Node_tools.c (get_destination() returns destination ID, get_hop_id() returns last node id, get_source_id() returns the origin node.
