### ISSUE TITLE
fsm send_deploy

### ISSUE THREAD

**Issue by reboss** [reboss/RapidOnsetAdHocNetwork#16]
- [ ] remove SEND_DEPLOY_INIT because as of now it does nothing
- [ ] add tcv_wnp() function before build_packet()
- [ ] ensure tcv_endp() isn't called on an already ended packet when if (cont) evaluates to true (I'm kind of unsure what is happening here)

**Comment by Shibbywan** [comment]
>  remove SEND_DEPLOY_INIT because as of now it does nothing
    
 my_id is an extern int which gets the ID from app.cc that the node sets. It just builds a 
     DEPLOY packet

>   ensure tcv_endp() isn't called on an already ended packet when if (cont) evaluates to true (I'm kind of unsure what is happening here)
      
if cont is true, the node will keep sending DEPLOY packets. When the node receives a    "DEPLOYED" packet, cont is set to 0 and it "shuts up". tcv_endp() was my mistake, I was half asleep. I believe that has to be tcv_wnp().

**Comment by reboss** [comment]
It builds a deploy packet but then is it supposed to do something with it?  Because the packet is redefined anyways inside of the next state.  Also, the scope of packet is only within the initial state in which nothing is done with it.

**Comment by Shibbywan** [comment]
Oh yeah you're right, It should just be 1 state.

**Comment by Shibbywan** [comment]
fix is in my branch, check it out then close this issue if it makes sense.
