### ISSUE TITLE
node_tools.cc

### ISSUE THREAD

**Issue by ElliottSobek** [reboss/RapidOnsetAdHocNetwork#9]
- [x] PID, CID, MID
- [x] change_ids()
- [ ] quiet()
- [ ] setup()

**Comment by ChrisDubeau** [comment]
What would setup() and quiet() need to do in Node_tools? and change_ids() can be done by sending set_ids(address packet) where packet would contain the parent_ID and my_id and then Child_id is calculated

**Comment by Shibbywan** [comment]
I kind of have setup() as send_deploy in network.cc, and I have something
for shut up as well. Checkout my branch.

**Comment by ChrisDubeau** [comment]
Would they need side functions in node_tools at all? if not ill close this as the other 2 are done

**Comment by Shibbywan** [comment]
I'm not sure yet tbh.
